### ISSUE TITLE
Network TODO

### ISSUE THREAD

**Issue by 3y3** [node-inspector/node-inspector#687]
- [x] Handle request abort
- [x] Handle request timeout error
- [x] We listen for `response` event. This changes app behavior. (Is it a problem, or all works as expected?)
- [x] Check socketPath behavior
- [x] If there is no listeners for response data, response will be newer ended. It's expected, but maybe we need to specially handle this situation?
